/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Chassis Type
 * Id: fb52a7c7-1691-40f2-aa83-8c8d9d0aa452
 * Codename: chassis_type
 */
export type ChassisType = 'cab_chassis' | 'strip_chassis';
