/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Configuration Option Category
 * Id: bb8d77f0-5d42-466c-8750-2f181642bd05
 * Codename: configuration_option_type
 */
export type ConfigurationOptionCategory = 'accessories' | 'charger' | 'chassis' | 'powertrain' | 'shelving' | 'upfit';
