/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Configuration Option Category
 * Id: 3d0b907c-8952-4377-b730-5112c17d5d90
 * Codename: configuration_option_category
 */
export type ConfigurationOptionCategory =
    | 'accessories'
    | 'body_style'
    | 'charger'
    | 'chassis'
    | 'drivetrain'
    | 'model'
    | 'others'
    | 'powertrain'
    | 'shelving'
    | 'upfit'
    | 'upholstery';
