/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Manufacturer
 * Id: baf696cb-0310-4692-a38b-86c1b8a61405
 * Codename: manufacturer
 */
export type Manufacturer =
    | 'abb'
    | 'aes'
    | 'chargepoint'
    | 'eavx'
    | 'eavx_reading'
    | 'eavx_test'
    | 'eby'
    | 'hackney'
    | 'knapheide'
    | 'local_manufacturer'
    | 'morgan_corp'
    | 'noco'
    | 'stellar'
    | 'stonebrooke'
    | 'subzero';
