/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Pool Inventory Reservation Status
 * Id: b8221e99-47ed-4438-b9aa-1dd7e88e167d
 * Codename: pool_inventory_reservation_status
 */
export type PoolInventoryReservationStatus = 'available' | 'closed' | 'reserved';
