/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Quote Statuses
 * Id: 95cce1e9-530d-434d-b39f-7af6fcd61112
 * Codename: quote_status
 */
export type QuoteStatuses =
    | 'closed'
    | 'delivered'
    | 'in_production'
    | 'in_transit'
    | 'order_processing'
    | 'quote_accepted'
    | 'quote_generated';
