/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Vehicle Make
 * Id: 0d585ea9-d77b-452f-a774-d7757db1f908
 * Codename: vehicle_make
 */
export type VehicleMake = 'fernhay' | 'streetrod';
