/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Vehicle Model
 * Id: 07296820-f139-4c91-ac6e-70466be64830
 * Codename: vehicle_model
 */
export type VehicleModel = 'equad' | 'ewalker' | 'grit' | 'lux' | 'vintage';
