/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Vocation
 * Id: 657ed971-6802-4d1b-890d-6beb47499ba6
 * Codename: vocation
 */
export type Vocation = 'construction___maintenance' | 'industrial_services' | 'package_delivery' | 'utility_services';
