import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Customization Option Basic Details
 * Id: 6654bdab-2c77-428b-a357-2a1d2e59599d
 * Codename: customization_option_basic_details
 */
export type CustomizationOptionBasicDetails = IContentItem<{
    /**
     * Description (rich_text)
     * Required: false
     * Id: cd54650e-3337-420a-a0b5-afbe3b73e585
     * Codename: customization_option_basic_details__description
     */
    customization_option_basic_details__description: Elements.RichTextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 90f6dc19-08ce-49f5-ac33-9d380270056f
     * Codename: customization_option_basic_details__image
     */
    customization_option_basic_details__image: Elements.AssetsElement;

    /**
     * Option Image (asset)
     * Required: false
     * Id: b108c3b6-5404-4154-9710-adefbc8bfd12
     * Codename: customization_option_basic_details__option_image
     */
    customization_option_basic_details__option_image: Elements.AssetsElement;

    /**
     * Title (text)
     * Required: false
     * Id: 63bfb610-1d26-43ed-b055-c59b1eea424b
     * Codename: customization_option_basic_details__title
     */
    customization_option_basic_details__title: Elements.TextElement;
}>;
