import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * GVWR
 * Id: 199811dd-36ef-46be-af35-12fe05dc61c5
 * Codename: gvwr
 */
export type GVWR = IContentItem<{
    /**
     * GVWR Unit (multiple_choice)
     * Required: true
     * Id: ee48c526-39b2-42df-b5c8-b3376d7b85a9
     * Codename: gvwr__gvwr_unit
     */
    gvwr__gvwr_unit: Elements.MultipleChoiceElement;

    /**
     * GVWR Value (number)
     * Required: true
     * Id: 5b77bdda-5cda-4ec7-8030-73a666ebcee4
     * Codename: gvwr__gvwr_value
     *
     * Enter value in number
     */
    gvwr__gvwr_value: Elements.NumberElement;
}>;
