import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * leadtime
 * Id: 5cf10c73-97b5-43d8-83aa-1fcdd7f7a185
 * Codename: leadtime
 */
export type Leadtime = IContentItem<{
    /**
     * Leadtime Unit (multiple_choice)
     * Required: true
     * Id: 0563eeea-e128-445f-b02a-d867f12bffaa
     * Codename: leadtime__leadtime_unit
     */
    leadtime__leadtime_unit: Elements.MultipleChoiceElement;

    /**
     * Leadtime Value (number)
     * Required: false
     * Id: dd134e54-ed69-48d2-aed1-823a9660e944
     * Codename: leadtime__value
     *
     * Value in number
     */
    leadtime__value: Elements.NumberElement;
}>;
