import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Payload Capacity
 * Id: b82ff58b-b443-460d-bb27-eace978ef173
 * Codename: payload_capacity
 */
export type PayloadCapacity = IContentItem<{
    /**
     * Payload Capacity Unit (multiple_choice)
     * Required: true
     * Id: b5aa15bd-5f9b-49c7-848a-b3c1043c2869
     * Codename: payload_capacity__payload_capacity_unit
     */
    payload_capacity__payload_capacity_unit: Elements.MultipleChoiceElement;

    /**
     * Payload Capacity Value (number)
     * Required: true
     * Id: 1d9f91a5-7471-42f9-9b38-a0971ce9fdbf
     * Codename: payload_capacity__payload_capacity_value
     */
    payload_capacity__payload_capacity_value: Elements.NumberElement;
}>;
