import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * price snippet
 * Id: e4b9e350-23cf-4b0d-ac85-02d30776edaf
 * Codename: price
 */
export type PriceSnippet = IContentItem<{
    /**
     * Dealer Price Unit (multiple_choice)
     * Required: true
     * Id: 1f2904b9-7d57-4e96-95c2-d29d30bf6858
     * Codename: price__dealer_price_unit
     */
    price__dealer_price_unit: Elements.MultipleChoiceElement;

    /**
     * Dealer Price Value (number)
     * Required: true
     * Id: fa87a0a8-c7ae-41e5-b989-2b94e9364aad
     * Codename: price__dealer_price_value
     */
    price__dealer_price_value: Elements.NumberElement;

    /**
     * MSRP Price Unit (multiple_choice)
     * Required: true
     * Id: b8a6b469-6984-4ee7-8712-9851b4a739b7
     * Codename: price__price_unit
     */
    price__price_unit: Elements.MultipleChoiceElement;

    /**
     * MSRP Price Value (number)
     * Required: true
     * Id: c15b8589-4a2f-4dfd-bc7b-4e477ab2ebba
     * Codename: price__value
     *
     * Value in number
     */
    price__value: Elements.NumberElement;
}>;
