import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * weight
 * Id: 40e39da7-9661-4289-90e0-9736923e22ed
 * Codename: weight
 */
export type Weight = IContentItem<{
    /**
     * Weight Value (number)
     * Required: true
     * Id: de29de67-a522-4acc-b489-0aedbc6d8a20
     * Codename: weight__value
     *
     * Value in number
     */
    weight__value: Elements.NumberElement;

    /**
     * Weight Unit (multiple_choice)
     * Required: true
     * Id: 07b09b67-28c1-41c2-a87c-2c3f918c2a5f
     * Codename: weight__weight_unit
     */
    weight__weight_unit: Elements.MultipleChoiceElement;
}>;
