import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Address
 * Id: 5fe75c3a-775a-4fee-bf49-8b827debbdb6
 * Codename: address
 */
export type Address = IContentItem<{
    /**
     * Address (text)
     * Required: false
     * Id: e14bc0f3-db10-4702-966f-ed094c29425a
     * Codename: address
     */
    address: Elements.TextElement;

    /**
     * City (text)
     * Required: false
     * Id: de25bba5-450d-490e-8756-58e9200cdfa1
     * Codename: city
     */
    city: Elements.TextElement;

    /**
     * Country (text)
     * Required: false
     * Id: 066d02a8-8064-48bb-a425-b624a127a9dc
     * Codename: country
     */
    country: Elements.TextElement;

    /**
     * Entity (text)
     * Required: false
     * Id: f77063c5-9bfe-4700-b933-c3e4705dd847
     * Codename: entity
     */
    entity: Elements.TextElement;

    /**
     * Provider Name (text)
     * Required: false
     * Id: a0233723-5d67-4ee8-90a8-a44f537ed1d7
     * Codename: provider_name
     */
    provider_name: Elements.TextElement;

    /**
     * Ship Through Code (text)
     * Required: false
     * Id: a4f58930-3a03-499c-a91f-f50f607a030a
     * Codename: ship_through_code
     */
    ship_through_code: Elements.TextElement;

    /**
     * State (text)
     * Required: false
     * Id: 955c217f-525b-4dba-aaa8-0bcc7dd85447
     * Codename: state
     */
    state: Elements.TextElement;

    /**
     * Zip Code (text)
     * Required: false
     * Id: 946fbf5d-4ce3-48a4-b476-1a9abbf13a60
     * Codename: zip_code
     */
    zip_code: Elements.TextElement;
}>;
