import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * App Settings
 * Id: 5f51f6f7-c964-4053-b204-4bda5576f644
 * Codename: app_settings
 */
export type AppSettings = IContentItem<{
    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 630d29e1-8df4-4f69-b817-2985ddc83543
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Header Logo PNG (asset)
     * Required: false
     * Id: eeb85cf1-5db4-41f7-a1d5-33a6cfa3bbe3
     * Codename: header_logo_png
     */
    header_logo_png: Elements.AssetsElement;

    /**
     * Header Logo SVG (asset)
     * Required: false
     * Id: 0e62fffe-3f7b-465a-92eb-05b03cd58ab0
     * Codename: header_logo_svg
     */
    header_logo_svg: Elements.AssetsElement;

    /**
     * Login Banner Image PNG (asset)
     * Required: false
     * Id: 685d55ff-200d-49c2-b1e4-68af2216cd57
     * Codename: login_banner_image_png
     */
    login_banner_image_png: Elements.AssetsElement;

    /**
     * Login Banner Image SVG (asset)
     * Required: false
     * Id: fed413c1-9324-4b89-b332-05f1d5464e6c
     * Codename: login_banner_image_svg
     */
    login_banner_image_svg: Elements.AssetsElement;

    /**
     * Logo PNG (asset)
     * Required: false
     * Id: faed871a-4818-4362-b40a-b3ab2246374e
     * Codename: logo_png
     */
    logo_png: Elements.AssetsElement;

    /**
     * Logo SVG (asset)
     * Required: false
     * Id: 1a468aed-d268-4bff-b5cd-a9e5cfca99c6
     * Codename: logo_svg
     */
    logo_svg: Elements.AssetsElement;

    /**
     * Misc Active Color (text)
     * Required: false
     * Id: a75e2e3e-f8d4-403a-a4c7-3e7c9ab648f3
     * Codename: misc_active_color
     *
     * Color for selected filter, selected tab etc.
     */
    misc_active_color: Elements.TextElement;

    /**
     * Name (text)
     * Required: false
     * Id: 58f6d9ee-db0f-439c-85ef-21eb1478374b
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Nav Link Active Color (text)
     * Required: false
     * Id: c4dd128b-d7e8-45a9-9ade-51a1b42da06d
     * Codename: nav_link_active_color
     *
     * Value should be CSS color value
     */
    nav_link_active_color: Elements.TextElement;

    /**
     * Primary Color (text)
     * Required: false
     * Id: 010729a0-a82f-4c7c-870e-33efa557a488
     * Codename: primary_color
     */
    primary_color: Elements.TextElement;

    /**
     * Primary Hover Color (text)
     * Required: false
     * Id: c9fe9093-4e03-48aa-92bc-e3bc546dffec
     * Codename: primary_hover_color
     *
     * Color for buttons or links when hovered
     */
    primary_hover_color: Elements.TextElement;

    /**
     * Secondary Color (text)
     * Required: false
     * Id: a3da08e8-d4ce-46b7-8e40-49fcf1a20436
     * Codename: secondary_color
     */
    secondary_color: Elements.TextElement;

    /**
     * Sidebar Logo PNG (asset)
     * Required: false
     * Id: 77eedc8c-a442-4ec3-ba1b-b5421e7330a3
     * Codename: sidebar_logo_png
     */
    sidebar_logo_png: Elements.AssetsElement;

    /**
     * Sidebar Logo SVG (asset)
     * Required: false
     * Id: 6de2f703-97a7-4912-bc3b-74cae419f170
     * Codename: sidebar_logo_svg
     */
    sidebar_logo_svg: Elements.AssetsElement;

    /**
     * Splash Screen Loader Color 1 (text)
     * Required: false
     * Id: 28e83c87-fbfb-4ec5-a2e9-64128a59e123
     * Codename: splash_screen_loader_color_1
     */
    splash_screen_loader_color_1: Elements.TextElement;

    /**
     * Splash Screen Loader Color 2 (text)
     * Required: false
     * Id: 7f439e37-be9f-4b08-a305-b251504999c0
     * Codename: splash_screen_loader_color_2
     */
    splash_screen_loader_color_2: Elements.TextElement;

    /**
     * Splash Screen Loader Color 3 (text)
     * Required: false
     * Id: dd5bfcf0-5ea1-475c-811c-be0d22229a09
     * Codename: splash_screen_loader_color_3
     */
    splash_screen_loader_color_3: Elements.TextElement;

    /**
     * Splash Screen Logo PNG (asset)
     * Required: false
     * Id: ccad018d-5959-4f5a-a712-4960801dc002
     * Codename: splash_screen_logo_png
     */
    splash_screen_logo_png: Elements.AssetsElement;

    /**
     * Splash Screen Logo SVG (asset)
     * Required: false
     * Id: 67c61f1b-0aa1-4e64-bbe5-f8c12e064e10
     * Codename: splash_screen_logo_svg
     */
    splash_screen_logo_svg: Elements.AssetsElement;
}>;
