import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Documents } from './vehicle_documents';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Charger
 * Id: cd85559e-a2f8-4a17-bf72-062f049efc37
 * Codename: charger
 */
export type Charger = IContentItem<{
    /**
     * Additional Specifications (rich_text)
     * Required: false
     * Id: e91f19c4-65d2-4fd6-845f-3a14d4011e59
     * Codename: additional_specs
     */
    additional_specs: Elements.RichTextElement;

    /**
     * Documents (modular_content)
     * Required: false
     * Id: a3df37b2-2f6b-405f-a135-47f47bb889b8
     * Codename: documents
     */
    documents: Elements.LinkedItemsElement<Documents>;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: bd51d858-0fcf-42ce-a037-14cb15c4e9f4
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: 0ec59f53-965c-4140-a6cd-8d7b382ab0f8
     * Codename: price_c3ed960
     */
    price_c3ed960: Elements.RichTextElement;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
