import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Accessories } from './vehicle_accessories';
import { type ChassisType } from '../taxonomies/chassis_type';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Documents } from './vehicle_documents';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Paint } from './vehicle_paint';
import { type Shelving } from './vehicle_shelving';
import { type Upfit } from './vehicle_upfit';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Test Content Type
 * Id: 4ed4ed6b-f4a5-4489-83f2-c927e49f294d
 * Codename: chassis__copy_
 */
export type TestContentType = IContentItem<{
    /**
     * Accessories (modular_content)
     * Required: false
     * Id: 825e5ce5-6ace-4793-9dae-9daf5639c144
     * Codename: accessories
     */
    accessories: Elements.LinkedItemsElement<Accessories>;

    /**
     * Documents (modular_content)
     * Required: false
     * Id: 6c695ada-d658-4ffc-a02f-e3159e81afc1
     * Codename: documents
     */
    documents: Elements.LinkedItemsElement<Documents>;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 0850e2ba-e3b0-485e-b44b-6627f2446208
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Linked Test Content Type (modular_content)
     * Required: false
     * Id: 196e36bb-bd70-48cb-9850-b7e559d9fbf9
     * Codename: linked_test_content_type
     */
    linked_test_content_type: Elements.LinkedItemsElement<TestContentType>;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: d20977a0-602f-4014-a6e4-f34520e86425
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Model 3D (asset)
     * Required: false
     * Id: 93007006-673d-41a4-9f17-cacd1a4dd0ae
     * Codename: model_3d
     */
    model_3d: Elements.AssetsElement;

    /**
     * Paint (modular_content)
     * Required: false
     * Id: 9baa4a8d-938b-4cdf-bb58-813567594509
     * Codename: paint
     */
    paint: Elements.LinkedItemsElement<Paint>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: ec597fbb-d344-444f-9cbd-af8d46f57b42
     * Codename: price_1cad98a
     */
    price_1cad98a: Elements.RichTextElement;

    /**
     * Shelving (modular_content)
     * Required: false
     * Id: 9ac9c9b2-e35f-4340-a978-f9d394d638d5
     * Codename: shelving
     */
    shelving: Elements.LinkedItemsElement<Shelving>;

    /**
     * Chassis Type (taxonomy)
     * Required: true
     * Id: 8f9bfcd8-5efb-4723-a2e9-fb0f27c149ff
     * Codename: type
     */
    type: Elements.TaxonomyElement<ChassisType>;

    /**
     * Upfits (modular_content)
     * Required: false
     * Id: ce6e3b0e-dba7-427b-800b-633ae144916d
     * Codename: untitled_linked_items
     */
    untitled_linked_items: Elements.LinkedItemsElement<Upfit>;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
