import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ChassisType } from '../taxonomies/chassis_type';
import { type ConfigurationOptionCategory } from '../taxonomies/configuration_option_category';
import { type ConfigurationSection } from './configuration_section';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Documents } from './vehicle_documents';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Paint } from './vehicle_paint';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Configuration Option
 * Id: 993765e2-9923-46f7-b8d1-4c7ca7d3dc1d
 * Codename: configuration_option
 */
export type ConfigurationOption = IContentItem<{
    /**
     * Additional Specifications (rich_text)
     * Required: false
     * Id: a592d4cf-5ec2-4832-9e40-3c969e297df5
     * Codename: additional_specifications
     */
    additional_specifications: Elements.RichTextElement;

    /**
     * Configuration Sections (modular_content)
     * Required: false
     * Id: c4bd7815-6c27-40b1-a0cd-9a55c85de97f
     * Codename: configuration_sections
     */
    configuration_sections: Elements.LinkedItemsElement<ConfigurationSection>;

    /**
     * Documents (modular_content)
     * Required: false
     * Id: 07ef717a-9396-40dc-a104-0c3a45524c3e
     * Codename: documents
     */
    documents: Elements.LinkedItemsElement<Documents>;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 6db99151-b992-4454-99a0-fe1a987e2455
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: cef9f889-2fbe-4da2-855e-de5712036db2
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Model 3D (asset)
     * Required: false
     * Id: 318cf2cb-bdcf-4453-b587-cc97e8b18eca
     * Codename: model_3d
     */
    model_3d: Elements.AssetsElement;

    /**
     * Configuration Option Category (taxonomy)
     * Required: false
     * Id: 0e9a27e7-a320-452f-aab1-0d026649f4e1
     * Codename: option_category
     */
    option_category: Elements.TaxonomyElement<ConfigurationOptionCategory>;

    /**
     * Paint Options (modular_content)
     * Required: false
     * Id: 7e7b7b60-1d7e-4c5f-89c0-7146e5a490c6
     * Codename: paint_options
     */
    paint_options: Elements.LinkedItemsElement<Paint>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: e2693868-6e1c-4b5d-8b5e-d445c8730559
     * Codename: price_1cad98a
     */
    price_1cad98a: Elements.RichTextElement;

    /**
     * Receiver (text)
     * Required: false
     * Id: c53fd0c7-efc8-4404-bab7-b181021b61c5
     * Codename: receiver
     */
    receiver: Elements.TextElement;

    /**
     * Chassis Type (taxonomy)
     * Required: false
     * Id: 1a52ca09-d4cd-4728-ba85-e690797f9be8
     * Codename: type
     */
    type: Elements.TaxonomyElement<ChassisType>;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
