import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type ConfigurationOption } from './configuration_option';
import { type ConfigurationOptionCategory } from '../taxonomies/configuration_option_category';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Configuration Section
 * Id: 42c6c6c6-6a61-4058-9258-f97bdcb3c611
 * Codename: configuration_section
 */
export type ConfigurationSection = IContentItem<{
    /**
     * Configuration Option Category (taxonomy)
     * Required: false
     * Id: 65b1f541-7edf-40f9-bceb-df8e69a4b407
     * Codename: configuration_option_category
     */
    configuration_option_category: Elements.TaxonomyElement<ConfigurationOptionCategory>;

    /**
     * Description (text)
     * Required: false
     * Id: dea256b9-1d65-4a22-abc6-525165de33f4
     * Codename: description
     */
    description: Elements.TextElement;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 8c08d14f-8e59-4159-8a26-bcb267339fd9
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Options (modular_content)
     * Required: false
     * Id: 8b405105-428e-424a-a2ef-1df432e6cf79
     * Codename: options
     */
    options: Elements.LinkedItemsElement<ConfigurationOption>;

    /**
     * Title (text)
     * Required: true
     * Id: 3da35473-a4a7-421e-8992-3119bcf90d26
     * Codename: title
     */
    title: Elements.TextElement;
}>;
