import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Customer
 * Id: edca07ff-518e-4f8e-aab9-e932767285b9
 * Codename: customer
 */
export type Customer = IContentItem<{
    /**
     * Address (text)
     * Required: false
     * Id: 9e3e8fc1-ad77-46b5-b1dc-5034bee88c1a
     * Codename: address
     */
    address: Elements.TextElement;

    /**
     * Buyer Name (text)
     * Required: true
     * Id: 4bbb985d-748b-464e-9c41-7e28f541ea4a
     * Codename: buyer_name
     */
    buyer_name: Elements.TextElement;

    /**
     * City (text)
     * Required: false
     * Id: a67761c7-eb98-46b6-bb38-f2ad1ba447fe
     * Codename: city
     */
    city: Elements.TextElement;

    /**
     * Co-Buyer Name (text)
     * Required: false
     * Id: 1bee1c71-fcb4-4e43-a67d-7a21fdf94d54
     * Codename: co_buyer_name
     */
    co_buyer_name: Elements.TextElement;

    /**
     * Country (text)
     * Required: false
     * Id: 2f7f8a04-37e5-4ae9-8d21-fec177a4ccfd
     * Codename: country
     */
    country: Elements.TextElement;

    /**
     * Customer Creator Email (text)
     * Required: false
     * Id: 2bb0ae6b-f6c0-4fbe-b815-929d1821ebc6
     * Codename: customer_creator_email
     */
    customer_creator_email: Elements.TextElement;

    /**
     * Deposit Percentage (number)
     * Required: true
     * Id: 732f2880-3ca7-475a-9f37-8307e7412805
     * Codename: deposit_percentage
     */
    deposit_percentage: Elements.NumberElement;

    /**
     * Email (text)
     * Required: true
     * Id: 29b5d772-46b6-4ed8-8beb-1fbf9f7f112a
     * Codename: email
     */
    email: Elements.TextElement;

    /**
     * Phone (text)
     * Required: false
     * Id: 882c6fcb-d9ed-4091-8129-f0b5660077d1
     * Codename: phone
     */
    phone: Elements.TextElement;

    /**
     * State (text)
     * Required: false
     * Id: 3d09a5b7-c968-43cc-8955-14a608d25195
     * Codename: state
     */
    state: Elements.TextElement;

    /**
     * User Email Domain (text)
     * Required: false
     * Id: 96542c8f-ad1f-4d64-a5bc-ecaa073f37e0
     * Codename: user_email_domain
     */
    user_email_domain: Elements.TextElement;

    /**
     * User ID (text)
     * Required: false
     * Id: b1a841e1-7eee-4061-8445-b0a36edd1731
     * Codename: user_id
     */
    user_id: Elements.TextElement;

    /**
     * WAN (text)
     * Required: false
     * Id: 0f7aeace-898c-418b-a564-aa17ee23e016
     * Codename: wan
     */
    wan: Elements.TextElement;

    /**
     * Zip Code (text)
     * Required: false
     * Id: 498f3ed4-73b9-4e93-8fea-91051bc6adf6
     * Codename: zip_code
     */
    zip_code: Elements.TextElement;
}>;
