import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Dashboard
 * Id: 23bc3408-d892-4beb-8f94-61d6615ff1dc
 * Codename: dashboard
 */
export type Dashboard = IContentItem<{
    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 5f363108-6e03-4ea8-9c25-ebdc842cfa75
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: 18b8de0a-3e9d-45e3-9458-a484a4bf1434
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: 124dbc4e-032d-4e60-b1f5-ba35f5f13a0e
     * Codename: price
     */
    price: Elements.RichTextElement;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
