import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Dealer
 * Id: 61ffdb75-3c33-4ed7-aad0-dfed810b20ce
 * Codename: dealer
 */
export type Dealer = IContentItem<{
    /**
     * Address (text)
     * Required: false
     * Id: 5917e785-0c68-47f6-b04e-3fa89e388675
     * Codename: address
     */
    address: Elements.TextElement;

    /**
     * City (text)
     * Required: false
     * Id: 5873f49c-0cef-41b1-b5f3-07d9d886d5fb
     * Codename: city
     */
    city: Elements.TextElement;

    /**
     * Country (text)
     * Required: false
     * Id: f7942550-dd3f-49bc-a9a4-618e33ee6c12
     * Codename: country
     */
    country: Elements.TextElement;

    /**
     * Dealership Name (text)
     * Required: false
     * Id: 789c0987-8784-48c2-86c1-85c3277ab992
     * Codename: dealership_name
     */
    dealership_name: Elements.TextElement;

    /**
     * Email (text)
     * Required: true
     * Id: 66d6c01e-0b8c-4845-8b86-d4724a2c810b
     * Codename: email
     */
    email: Elements.TextElement;

    /**
     * External ID (text)
     * Required: false
     * Id: 909107cb-0ee0-4056-90eb-3be7d23460a9
     * Codename: external_id
     */
    external_id: Elements.TextElement;

    /**
     * Job Title (text)
     * Required: false
     * Id: 4891c576-aa14-4c3a-8e4a-475ca2e83d23
     * Codename: job_title
     */
    job_title: Elements.TextElement;

    /**
     * Name (text)
     * Required: true
     * Id: 475c7651-a01a-44b0-b295-a7c97ea3724c
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Phone (text)
     * Required: false
     * Id: de00b8ee-41ec-4ba9-ac6f-b0b4e8600815
     * Codename: phone
     */
    phone: Elements.TextElement;

    /**
     * State (text)
     * Required: false
     * Id: 3622a0bd-2abb-49c6-bc9f-b63b32d6fd7d
     * Codename: state
     */
    state: Elements.TextElement;

    /**
     * Zip Code (text)
     * Required: false
     * Id: d7eed85d-fffc-48ee-8b62-cf4d31eb8ec2
     * Codename: zip_code
     */
    zip_code: Elements.TextElement;
}>;
