import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Email
 * Id: 849ecee6-3822-49f6-9a23-9c566f6c565f
 * Codename: email_53b77bb
 */
export type Email = IContentItem<{
    /**
     * Email (text)
     * Required: false
     * Id: 169c7475-1965-4574-8dbc-c469cd1ffb95
     * Codename: email
     */
    email: Elements.TextElement;
}>;
