import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Help Center-Tutorial
 * Id: 9151b380-4df1-4467-8ef8-bd0dafb2f5c7
 * Codename: help_center_tutorial
 */
export type HelpCenterTutorial = IContentItem<{
    /**
     * Image (asset)
     * Required: false
     * Id: ecf67d58-575c-40c6-bc0c-4a74931b55a2
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Link Title (text)
     * Required: false
     * Id: 1ec63ff8-0d17-42fa-aa4a-dd6c63b62694
     * Codename: link_title
     */
    link_title: Elements.TextElement;

    /**
     * Link URL (text)
     * Required: false
     * Id: f4c67f9e-69a1-45fc-ae2f-7d99cba588fd
     * Codename: link_url
     */
    link_url: Elements.TextElement;

    /**
     * Title (text)
     * Required: true
     * Id: 3e4f41ad-08c8-4d3b-a3ba-100461f77b37
     * Codename: title
     */
    title: Elements.TextElement;
}>;
