import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Help Center-FAQ
 * Id: 28dcfa34-a997-45e0-9e8b-da29edf64e90
 * Codename: help_center_faq
 */
export type HelpCenterFAQ = IContentItem<{
    /**
     * Answer (rich_text)
     * Required: true
     * Id: a9d60e00-e02c-4619-913c-cb9ca38e222b
     * Codename: answer
     */
    answer: Elements.RichTextElement;

    /**
     * Question (text)
     * Required: true
     * Id: 3d2fa8df-73f0-4824-956c-8508c72f72b9
     * Codename: question
     */
    question: Elements.TextElement;
}>;
