import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Pool Inventory Email
 * Id: 85d9d57a-5b78-4fe1-bd6f-0c0067fe5975
 * Codename: pool_inventory_email
 */
export type PoolInventoryEmail = IContentItem<{
    /**
     * Emails (rich_text)
     * Required: false
     * Id: 22dc944b-3f62-4e05-96df-7a867c304a37
     * Codename: emails
     */
    emails: Elements.RichTextElement;
}>;
