import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type PoolInventoryReservationStatus } from '../taxonomies/pool_inventory_reservation_status';
import { type Vehicle } from './vehicle';
import { type VehicleModel } from '../taxonomies/vehicle_model';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Pool Inventory
 * Id: 052f7bf7-a903-4e00-ab9d-ada536bb3e76
 * Codename: pool_inventory
 */
export type PoolInventory = IContentItem<{
    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: 7f09173a-6688-4cc0-85d6-2537f947819f
     * Codename: body_manufacturer
     */
    body_manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Body Type (text)
     * Required: false
     * Id: 38ed4e85-5555-47d6-8f8c-b342a5dcc0ca
     * Codename: body_type
     */
    body_type: Elements.TextElement;

    /**
     * Chassis Price Unit (multiple_choice)
     * Required: false
     * Id: 8c24abc0-2462-404c-8cc2-f5371cc2a7ef
     * Codename: chassis_price_unit
     */
    chassis_price_unit: Elements.MultipleChoiceElement;

    /**
     * Chassis Price Value (number)
     * Required: false
     * Id: b6678710-5e16-484c-9b84-71bbcd8b3717
     * Codename: chassis_price_value
     */
    chassis_price_value: Elements.NumberElement;

    /**
     * Dealer ID (text)
     * Required: false
     * Id: eac337c2-b423-4d36-8f1d-aa04705172dc
     * Codename: dealer_id
     */
    dealer_id: Elements.TextElement;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 7e6cd786-e329-4592-9744-ade942f696b2
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Location (text)
     * Required: false
     * Id: 9517405f-7666-41d6-a06c-4d67a19366ca
     * Codename: location
     */
    location: Elements.TextElement;

    /**
     * Pool Inventory Reservation Status (taxonomy)
     * Required: false
     * Id: 2cb30a5e-b92e-4a62-9bd6-f33e43c71349
     * Codename: status
     */
    status: Elements.TaxonomyElement<PoolInventoryReservationStatus>;

    /**
     * Upfit Price Unit (multiple_choice)
     * Required: false
     * Id: 8b64a4e1-fd8d-42c6-960f-b2a2d913b01d
     * Codename: upfit_price_unit
     */
    upfit_price_unit: Elements.MultipleChoiceElement;

    /**
     * Upfit Price Value (number)
     * Required: false
     * Id: bb02aa83-dfb2-4201-8a42-0f4089e4827c
     * Codename: upfit_price_value
     */
    upfit_price_value: Elements.NumberElement;

    /**
     * Vehicle (modular_content)
     * Required: false
     * Id: 93b732ec-37e0-4d86-9697-26463b2e8505
     * Codename: vehicle
     */
    vehicle: Elements.LinkedItemsElement<Vehicle>;

    /**
     * Vehicle Model (taxonomy)
     * Required: false
     * Id: b5a7e6e2-9b60-4658-8ffc-7cf4ab25e036
     * Codename: vehicle_model
     */
    vehicle_model: Elements.TaxonomyElement<VehicleModel>;

    /**
     * VIN (text)
     * Required: false
     * Id: 442f9423-cccc-4385-9caa-dd23aaf5234c
     * Codename: vin
     */
    vin: Elements.TextElement;
}>;
