import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Powertrain
 * Id: 0c0f811d-adc6-48a7-b1db-47e2ef3bf51d
 * Codename: powertrain
 */
export type Powertrain = IContentItem<{
    /**
     * Additional Specifications (rich_text)
     * Required: false
     * Id: 7ec0b1e9-51c9-463f-8f30-211398b94f41
     * Codename: additional_specifications
     */
    additional_specifications: Elements.RichTextElement;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 06ba88f8-4ef5-4e9d-a0c2-6727ca440835
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Price (rich_text)
     * Required: false
     * Id: a45f4da7-ad2c-4d10-8fe1-c30086117fc9
     * Codename: price_cc4a06b
     */
    price_cc4a06b: Elements.RichTextElement;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
