import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Price
 * Id: dd7e3da1-309c-4685-a715-65ec05843233
 * Codename: price_5737012
 */
export type Price = IContentItem<{
    /**
     * Entity (text)
     * Required: false
     * Id: ecfc3cb5-05ed-475d-b234-b6d2784b3443
     * Codename: entity
     *
     * Value is either 'default' or dealer's email
     */
    entity: Elements.TextElement;

    /**
     * Unit (multiple_choice)
     * Required: false
     * Id: cf69789d-5289-4699-a508-d16b489fd385
     * Codename: unit
     */
    unit: Elements.MultipleChoiceElement;

    /**
     * Value (number)
     * Required: false
     * Id: b58af389-2ffd-4d5b-af44-8831a1c42ba5
     * Codename: value
     */
    value: Elements.NumberElement;
}>;
