import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Product Specifications
 * Id: 15550ee2-0f50-49ac-9fe0-16eff1001b49
 * Codename: product_specifications
 */
export type ProductSpecifications = IContentItem<{
    /**
     * Title (text)
     * Required: true
     * Id: 5017709a-f88e-4b25-8841-58e5b369ec15
     * Codename: title
     *
     * Enter specification title like Input Voltage, Output Voltage. Power Delivery etc.
     */
    title: Elements.TextElement;

    /**
     * Value (text)
     * Required: false
     * Id: e706e4d2-88d6-4f93-967d-c9546961488c
     * Codename: value
     */
    value: Elements.TextElement;
}>;
