import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Accessories } from './vehicle_accessories';
import { type Charger } from './charger';
import { type Chassis } from './vehicle_chassis';
import { type Customer } from './customer';
import { type Dealer } from './dealer';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Paint } from './vehicle_paint';
import { type PayloadCapacity } from '../content-type-snippets/payload_capacity';
import { type Powertrain } from './powertrain';
import { type PriceSnippet } from '../content-type-snippets/price';
import { type QuoteStatus } from './quote_status';
import { type Shelving } from './vehicle_shelving';
import { type Upfit } from './vehicle_upfit';
import { type Vehicle } from './vehicle';
import { type VehicleModel } from '../taxonomies/vehicle_model';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Quote
 * Id: 6c3db8a6-3dc8-4c5f-9354-308bd574b276
 * Codename: quote
 */
export type Quote = IContentItem<{
    /**
     * Accessories (modular_content)
     * Required: false
     * Id: fc034cb5-f829-44c2-960a-8ec105473e8e
     * Codename: accessories
     */
    accessories: Elements.LinkedItemsElement<Accessories>;

    /**
     * Accessories Ship Through Address (rich_text)
     * Required: false
     * Id: 5fe369bb-54d8-46bb-82f0-9535e38813d2
     * Codename: accessories_ship_through_address
     */
    accessories_ship_through_address: Elements.RichTextElement;

    /**
     * BOM File Link (text)
     * Required: false
     * Id: c30db3c8-e2e4-45c0-a85a-723cb7425522
     * Codename: bom_file_link
     */
    bom_file_link: Elements.TextElement;

    /**
     * Charger (modular_content)
     * Required: false
     * Id: 167900e6-3049-420e-a149-a6a7548a13a9
     * Codename: charger
     */
    charger: Elements.LinkedItemsElement<Charger>;

    /**
     * Charger Ship Through Address (rich_text)
     * Required: false
     * Id: 3b712625-4b09-4747-9549-0b7bdecc9ed2
     * Codename: charger_ship_through_address
     */
    charger_ship_through_address: Elements.RichTextElement;

    /**
     * Customer (modular_content)
     * Required: false
     * Id: 95d0a3ac-3da0-4efa-af1e-4369ac0e5462
     * Codename: customer
     */
    customer: Elements.LinkedItemsElement<Customer>;

    /**
     * Date Created (date_time)
     * Required: true
     * Id: f6d4aeb7-a1cc-4a65-8f9d-02b934b8025d
     * Codename: date_created
     */
    date_created: Elements.DateTimeElement;

    /**
     * Dealer (modular_content)
     * Required: false
     * Id: e396f773-342f-4878-a344-e27b536b8d65
     * Codename: dealer
     */
    dealer: Elements.LinkedItemsElement<Dealer>;

    /**
     * Dealer Email (text)
     * Required: false
     * Id: bb0ad2ae-ce77-4c45-aa82-7058384a7e7c
     * Codename: dealer_email
     */
    dealer_email: Elements.TextElement;

    /**
     * Dealer ID (text)
     * Required: false
     * Id: 21690864-a9b5-4059-b921-064fd95941d9
     * Codename: dealer_id
     */
    dealer_id: Elements.TextElement;

    /**
     * Dealership Name (text)
     * Required: false
     * Id: b307e40a-0fa3-4915-a5c2-608228c41aa0
     * Codename: dealership_name
     */
    dealership_name: Elements.TextElement;

    /**
     * Description (text)
     * Required: false
     * Id: 8b065c0c-b8da-41bc-b530-3c8f24f16d39
     * Codename: description
     */
    description: Elements.TextElement;

    /**
     * Destination Address (rich_text)
     * Required: false
     * Id: 2bb44b46-e26c-486a-b27d-399618a9e047
     * Codename: destination_address
     */
    destination_address: Elements.RichTextElement;

    /**
     * Expiry Duration In Days (number)
     * Required: false
     * Id: 14576e88-2892-46dc-a379-fbdb39b83254
     * Codename: expiry_duration_in_days
     */
    expiry_duration_in_days: Elements.NumberElement;

    /**
     * Formatted ID (text)
     * Required: false
     * Id: d182a273-d425-40b0-85a3-b215397e46f9
     * Codename: formatted_id
     */
    formatted_id: Elements.TextElement;

    /**
     * Group (text)
     * Required: false
     * Id: 99104619-2a1c-40d7-90d9-3c492d1a43c0
     * Codename: group
     */
    group: Elements.TextElement;

    /**
     * Group ID (text)
     * Required: false
     * Id: 5b041e3f-47f4-4614-a5e5-87b4a3444fa6
     * Codename: group_id
     */
    group_id: Elements.TextElement;

    /**
     * Group Quantity (number)
     * Required: false
     * Id: 21777900-e2f4-45bd-9414-e621a7025254
     * Codename: group_quantity
     */
    group_quantity: Elements.NumberElement;

    /**
     * Group Vehicle Index (number)
     * Required: false
     * Id: fd8f8412-c84f-4b69-a9aa-826accf7ad0d
     * Codename: group_vehicle_index
     */
    group_vehicle_index: Elements.NumberElement;

    /**
     * OEM Order No (text)
     * Required: false
     * Id: 894b698c-216a-43af-bb48-1e3b115be1fd
     * Codename: oem_order_no
     */
    oem_order_no: Elements.TextElement;

    /**
     * Order Type (multiple_choice)
     * Required: true
     * Id: 6ccf6932-7718-4b8e-9cfd-190433610099
     * Codename: order_type
     */
    order_type: Elements.MultipleChoiceElement;

    /**
     * Paint (modular_content)
     * Required: false
     * Id: edccc30c-0060-4cf7-ab93-bc317e126763
     * Codename: paint
     */
    paint: Elements.LinkedItemsElement<Paint>;

    /**
     * Powertrain (modular_content)
     * Required: false
     * Id: a108166b-5fb2-4f3e-b41e-223f49ab1639
     * Codename: powertrain
     */
    powertrain: Elements.LinkedItemsElement<Powertrain>;

    /**
     * Quote File Link (text)
     * Required: false
     * Id: c5a35691-05a3-4a69-9b58-43186310ad3b
     * Codename: quote_file_link
     */
    quote_file_link: Elements.TextElement;

    /**
     * Quote ID (number)
     * Required: false
     * Id: 8ee0ce23-6f72-4177-81e1-6ad61f52247e
     * Codename: quote_id
     */
    quote_id: Elements.NumberElement;

    /**
     * Quote Timestamp id (text)
     * Required: false
     * Id: b817f5bf-f0b1-440d-bc79-383ec8378eed
     * Codename: quote_timestamp_id
     */
    quote_timestamp_id: Elements.TextElement;

    /**
     * Sales Manager Name (text)
     * Required: false
     * Id: 1a4d3353-2caf-4335-8e3c-d59f1ad78dae
     * Codename: sales_manager_name
     */
    sales_manager_name: Elements.TextElement;

    /**
     * Shelving (modular_content)
     * Required: false
     * Id: c43b2ac0-32ed-48a8-96bd-22fc37504121
     * Codename: shelving
     */
    shelving: Elements.LinkedItemsElement<Shelving>;

    /**
     * Signed Quote File Link (text)
     * Required: false
     * Id: d7fba458-c5ec-4075-88d9-7559b8fa4194
     * Codename: signed_quote_file_link
     */
    signed_quote_file_link: Elements.TextElement;

    /**
     * Status (modular_content)
     * Required: false
     * Id: bcdd7bb4-4f4e-4778-b76c-0c5d8613cfc1
     * Codename: status
     */
    status: Elements.LinkedItemsElement<QuoteStatus>;

    /**
     * Upfit Ship Through Address (rich_text)
     * Required: false
     * Id: a1e5e11d-0d92-4776-9b60-572f8ad5133a
     * Codename: upfit_ship_through_address
     */
    upfit_ship_through_address: Elements.RichTextElement;

    /**
     * Upfits (modular_content)
     * Required: false
     * Id: 5651d1dd-9997-4331-9218-c6dfe90c1cea
     * Codename: upfits
     */
    upfits: Elements.LinkedItemsElement<Upfit | Chassis>;

    /**
     * User Email Domain (text)
     * Required: false
     * Id: 4e454f44-9798-428d-86f2-0e6f09fd0b05
     * Codename: user_email_domain
     */
    user_email_domain: Elements.TextElement;

    /**
     * Vehicle (modular_content)
     * Required: false
     * Id: bbb63681-3493-4897-b9a0-8dab034657b9
     * Codename: vehicle
     */
    vehicle: Elements.LinkedItemsElement<Vehicle>;

    /**
     * Vehicle Model (taxonomy)
     * Required: true
     * Id: 545123fa-b7a5-4df1-82f5-95cbcda3bd92
     * Codename: vehicle_model
     */
    vehicle_model: Elements.TaxonomyElement<VehicleModel>;

    /**
     * Vehicle Quantity (number)
     * Required: true
     * Id: 9f6df4fc-e094-44d6-9a8c-d9862db44456
     * Codename: vehicle_quantity
     */
    vehicle_quantity: Elements.NumberElement;

    /**
     * Vehicle Quantity Index (number)
     * Required: false
     * Id: 23879f0a-1bf1-4bab-9ab9-272ea7fb228d
     * Codename: vehicle_quantity_index
     *
     * Zero-based index for vehicle number out of total 'Vehicle Quantity'For example, if 'Vehicle Quantity' is 2, possible index values are 0 and 1
     */
    vehicle_quantity_index: Elements.NumberElement;

    /**
     * VIN (text)
     * Required: false
     * Id: 76887a1f-6461-49c3-8681-9fa3a19b6937
     * Codename: vin
     */
    vin: Elements.TextElement;
}> &
    Leadtime &
    PayloadCapacity &
    PriceSnippet;
