import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type QuoteStatuses } from '../taxonomies/quote_status';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Quote Status
 * Id: 5610c268-6530-4dd5-bbdd-43eef1ba55e9
 * Codename: quote_status
 */
export type QuoteStatus = IContentItem<{
    /**
     * Group (multiple_choice)
     * Required: false
     * Id: 3bbd7efe-d8ea-4438-9bc6-208f2a75b96a
     * Codename: group
     */
    group: Elements.MultipleChoiceElement;

    /**
     * Quote Statuses (taxonomy)
     * Required: false
     * Id: d13ef3a6-1383-49e3-b2b9-76f9670c07fb
     * Codename: quote_status
     */
    quote_status: Elements.TaxonomyElement<QuoteStatuses>;

    /**
     * Title (text)
     * Required: true
     * Id: 5d457a68-d08b-4a5f-8a06-0711273d1cb6
     * Codename: title
     */
    title: Elements.TextElement;
}>;
