import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Quote Email
 * Id: e901a5c4-2fed-4755-9653-fcb558ddb19b
 * Codename: quote_email
 */
export type QuoteEmail = IContentItem<{
    /**
     * Emails (rich_text)
     * Required: false
     * Id: 0e9021da-d77c-4752-9247-2ae045a78bbb
     * Codename: emails
     */
    emails: Elements.RichTextElement;
}>;
