import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Accessories } from './vehicle_accessories';
import { type ChassisType } from '../taxonomies/chassis_type';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Documents } from './vehicle_documents';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Paint } from './vehicle_paint';
import { type Shelving } from './vehicle_shelving';
import { type Upfit } from './vehicle_upfit';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Chassis
 * Id: 371ff816-1322-4ff9-8689-4f42f58103e6
 * Codename: vehicle_chassis
 */
export type Chassis = IContentItem<{
    /**
     * Accessories (modular_content)
     * Required: false
     * Id: e53893c0-009b-4376-adb8-f12b6e578b85
     * Codename: accessories
     */
    accessories: Elements.LinkedItemsElement<Accessories>;

    /**
     * Documents (modular_content)
     * Required: false
     * Id: 8a5139a7-36d3-4b01-abdb-c523ffd15e52
     * Codename: documents
     */
    documents: Elements.LinkedItemsElement<Documents>;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 5b3545d3-c86e-47f1-8e8c-c70622023f1d
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: e32c3b6a-11c9-4951-9f33-b1d96e0a4a1e
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Model 3D (asset)
     * Required: false
     * Id: 0286cd17-8371-4e37-bbf8-f56e4a1555b8
     * Codename: model_3d
     */
    model_3d: Elements.AssetsElement;

    /**
     * Paint (modular_content)
     * Required: false
     * Id: 19e1de9b-c48f-4658-b72d-f803b8f697af
     * Codename: paint
     */
    paint: Elements.LinkedItemsElement<Paint>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: e39f3f6c-26e4-49b9-b0d5-b4f9546975d6
     * Codename: price_1cad98a
     */
    price_1cad98a: Elements.RichTextElement;

    /**
     * Shelving (modular_content)
     * Required: false
     * Id: b272ce84-6664-4bcb-8ae6-0003c9284c3d
     * Codename: shelving
     */
    shelving: Elements.LinkedItemsElement<Shelving>;

    /**
     * Chassis Type (taxonomy)
     * Required: true
     * Id: 1b0cba0f-666a-4754-aaf9-f87c037f0ea6
     * Codename: type
     */
    type: Elements.TaxonomyElement<ChassisType>;

    /**
     * Upfits (modular_content)
     * Required: false
     * Id: 3c84bfc8-db7d-4bad-9d9c-10c57e24ac85
     * Codename: untitled_linked_items
     */
    untitled_linked_items: Elements.LinkedItemsElement<Upfit>;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
