import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Accessories
 * Id: 294d5bb5-b580-44e4-b907-bd54bea7dc02
 * Codename: vehicle_accessories
 */
export type Accessories = IContentItem<{
    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: ea19f7f5-be58-4179-96f2-a405135b772c
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: 42e1619f-5fd9-4043-8441-1ef9e898d14e
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: c8546fb7-5d10-49c8-8be7-22a54500edfa
     * Codename: price_ccf9236
     */
    price_ccf9236: Elements.RichTextElement;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
