import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Vehicle } from './vehicle';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Vehicle Wrapper
 * Id: 3c818e4d-8bb7-4616-8c3e-99aadcc413b3
 * Codename: vehicle_wrapper
 */
export type VehicleWrapper = IContentItem<{
    /**
     * Vehicle (modular_content)
     * Required: false
     * Id: 8d2ea694-51b4-47b2-94a7-fe89b183d7fd
     * Codename: vehicle
     */
    vehicle: Elements.LinkedItemsElement<Vehicle>;
}>;
