import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Shelving
 * Id: f01cf7ff-47dd-498c-a2fd-6a50a15b3c09
 * Codename: vehicle_shelving
 */
export type Shelving = IContentItem<{
    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: e53c7775-54f0-4e21-8ed6-fb1f840b19ca
     * Codename: flags
     *
     * - 'Always Visible' means the option would show regardless of whether an 'Upfit' is selected or not.
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: a22991fb-e455-46be-a6e2-5c7b56d700f6
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Model 3D (asset)
     * Required: false
     * Id: 492d220c-9266-49bc-91c7-0d390436fbcd
     * Codename: model_3d
     */
    model_3d: Elements.AssetsElement;

    /**
     * Price (rich_text)
     * Required: false
     * Id: ed13dc06-1706-40a2-87fa-966fbaede01f
     * Codename: price_bb67268
     */
    price_bb67268: Elements.RichTextElement;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
