import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Documents
 * Id: fbadae3e-255c-4de6-a2cb-330db92b569d
 * Codename: vehicle_documents
 */
export type Documents = IContentItem<{
    /**
     * Spec Sheet (asset)
     * Required: false
     * Id: b23d7996-a293-4414-9896-27481c440e0e
     * Codename: spec_sheet
     */
    spec_sheet: Elements.AssetsElement;

    /**
     * Warranty Specification (asset)
     * Required: false
     * Id: 1c41dba9-67b2-4e7f-b94e-918eb185d9a6
     * Codename: warranty_specification
     */
    warranty_specification: Elements.AssetsElement;

    /**
     * Window Sticker (asset)
     * Required: false
     * Id: ef1d22f0-56a6-4a18-b389-0d351a19a6cb
     * Codename: window_sticker
     */
    window_sticker: Elements.AssetsElement;
}>;
