import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Accessories } from './vehicle_accessories';
import { type CustomizationOptionBasicDetails } from '../content-type-snippets/customization_option_basic_details';
import { type Documents } from './vehicle_documents';
import { type Leadtime } from '../content-type-snippets/leadtime';
import { type Manufacturer } from '../taxonomies/manufacturer';
import { type Paint } from './vehicle_paint';
import { type Shelving } from './vehicle_shelving';
import { type Vocation } from '../taxonomies/vocation';
import { type Weight } from '../content-type-snippets/weight';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Upfit
 * Id: 608e4cb7-a10c-4165-a769-b482af84dd4d
 * Codename: vehicle_upfit
 */
export type Upfit = IContentItem<{
    /**
     * Accessories (modular_content)
     * Required: false
     * Id: 63ec5960-4035-44a4-8223-8158fb1602dd
     * Codename: accessories
     */
    accessories: Elements.LinkedItemsElement<Accessories>;

    /**
     * Documents (modular_content)
     * Required: false
     * Id: 8af8f8bd-a7ef-46b4-af67-799014629cf4
     * Codename: documents
     */
    documents: Elements.LinkedItemsElement<Documents>;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: bf9ec713-2fda-4cb8-a944-af325feb5f29
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Manufacturer (taxonomy)
     * Required: false
     * Id: 9f1bfb43-ac67-4c0c-a229-8ab414717d67
     * Codename: manufacturer
     */
    manufacturer: Elements.TaxonomyElement<Manufacturer>;

    /**
     * Model 3D (asset)
     * Required: false
     * Id: 9c761e88-6214-4e67-aa2e-d47d96bfd69f
     * Codename: model_3d
     */
    model_3d: Elements.AssetsElement;

    /**
     * Paint (modular_content)
     * Required: false
     * Id: 04be1227-f5bf-4713-8033-5537f4fcec68
     * Codename: paint
     */
    paint: Elements.LinkedItemsElement<Paint>;

    /**
     * Price (rich_text)
     * Required: false
     * Id: d87fb963-a31f-423c-80fd-620db4648b96
     * Codename: price_a695c27
     */
    price_a695c27: Elements.RichTextElement;

    /**
     * Receiver (text)
     * Required: false
     * Id: afa60fc2-dfbe-4804-83ec-3923a0a9a6d2
     * Codename: receiver
     */
    receiver: Elements.TextElement;

    /**
     * Shelving (modular_content)
     * Required: false
     * Id: bd30c83d-c168-4edd-a568-479c16ca4f06
     * Codename: shelving
     */
    shelving: Elements.LinkedItemsElement<Shelving>;

    /**
     * Vocation (taxonomy)
     * Required: false
     * Id: 610e4187-e321-45fb-8ffe-e0baab7fe90c
     * Codename: vocation
     */
    vocation: Elements.TaxonomyElement<Vocation>;
}> &
    CustomizationOptionBasicDetails &
    Leadtime &
    Weight;
