import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Paint
 * Id: 8ca1ed85-cfad-4f8c-bcef-3df330b5175c
 * Codename: vehicle_paint
 */
export type Paint = IContentItem<{
    /**
     * Color Code (text)
     * Required: true
     * Id: dd033e40-975e-4dfa-8fda-f5f93c7e928e
     * Codename: color_code
     *
     * Enter hex code for color e.g. #FFFFFF
     */
    color_code: Elements.TextElement;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: 26b72a3b-9b8c-46a6-82b6-b57a0df74cd6
     * Codename: flags
     */
    flags: Elements.MultipleChoiceElement;

    /**
     * Name (text)
     * Required: false
     * Id: d282f167-59e1-4b76-a3cb-a73e787475cb
     * Codename: name
     *
     * Enter name of color e.g., White, Blue, Black etc.
     */
    name: Elements.TextElement;

    /**
     * Price (rich_text)
     * Required: false
     * Id: f291362b-1275-419b-aeaf-e1e7f3d5cb1c
     * Codename: price_dcef68c
     */
    price_dcef68c: Elements.RichTextElement;
}>;
