import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Charger } from './charger';
import { type Chassis } from './vehicle_chassis';
import { type ConfigurationSection } from './configuration_section';
import { type GVWR } from '../content-type-snippets/gvwr';
import { type Powertrain } from './powertrain';
import { type Upfit } from './vehicle_upfit';
import { type VehicleMake } from '../taxonomies/vehicle_make';
import { type VehicleModel } from '../taxonomies/vehicle_model';
import { type Vocation } from '../taxonomies/vocation';

/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Vehicle
 * Id: f5f13555-a394-4c44-bc97-1344d859616a
 * Codename: vehicle
 */
export type Vehicle = IContentItem<{
    /**
     * Chargers (modular_content)
     * Required: false
     * Id: 264624f5-634a-4b25-876c-64c89982b55e
     * Codename: chargers
     */
    chargers: Elements.LinkedItemsElement<Charger>;

    /**
     * Configuration Sections (modular_content)
     * Required: false
     * Id: 00d7006e-d1f5-41d5-a2b9-f8b8f7d5862e
     * Codename: configuration_sections
     */
    configuration_sections: Elements.LinkedItemsElement<ConfigurationSection>;

    /**
     * Description (rich_text)
     * Required: false
     * Id: 5e9d1246-63ad-414b-86f2-163660c7584e
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * Flags (multiple_choice)
     * Required: false
     * Id: a34cc28c-f107-45f9-a3d8-aec9ef3bc38d
     * Codename: flags_384b6cf
     */
    flags_384b6cf: Elements.MultipleChoiceElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 84515f1c-0354-47ab-8fee-e4c34700715f
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Vehicle Make (taxonomy)
     * Required: true
     * Id: 6bbdbbde-e8d5-47a4-9a5c-2f13a0dac14c
     * Codename: make
     */
    make: Elements.TaxonomyElement<VehicleMake>;

    /**
     * Vehicle Model (taxonomy)
     * Required: true
     * Id: fa562cc1-228b-4bc3-bf37-20f4b7780d76
     * Codename: model
     */
    model: Elements.TaxonomyElement<VehicleModel>;

    /**
     * Powertrain (modular_content)
     * Required: false
     * Id: 293b6f7d-e269-48e5-b2d8-13b89169a359
     * Codename: powertrain
     */
    powertrain: Elements.LinkedItemsElement<Powertrain>;

    /**
     * Chassis (modular_content)
     * Required: false
     * Id: 63318c1b-4c76-46aa-80ce-765a44a1d47b
     * Codename: untitled_linked_items
     */
    untitled_linked_items: Elements.LinkedItemsElement<Chassis>;

    /**
     * Upfits (modular_content)
     * Required: false
     * Id: d35838ff-4e28-4696-b140-cc9810c43229
     * Codename: upfits
     */
    upfits: Elements.LinkedItemsElement<Upfit>;

    /**
     * Vocation (taxonomy)
     * Required: false
     * Id: b1c79a8b-8aef-48c7-b0eb-e09a65c7716f
     * Codename: vocation
     */
    vocation: Elements.TaxonomyElement<Vocation>;
}> &
    GVWR;
