/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const assetFolders = {
    /**
     * 3D Models
     */
    _3DModels: {
        id: '385c8d77-8c0a-48bc-94b5-29691717146a',
        name: '3D Models',
        externalId: undefined,
        folders: {}
    },

    /**
     * Chasses
     */
    chasses: {
        id: 'ef77779c-bcb9-4987-bb81-0b93870e1441',
        name: 'Chasses',
        externalId: undefined,
        folders: {}
    },

    /**
     * Fernhay eQuad
     */
    fernhayEQuad: {
        id: 'f6dcd357-ee92-46d4-9a5d-6b832cdba99d',
        name: 'Fernhay eQuad',
        externalId: undefined,
        folders: {}
    },

    /**
     * Fernhay eWalker
     */
    fernhayEWalker: {
        id: '833e2612-7cc4-42f0-bb38-0e6a4291b262',
        name: 'Fernhay eWalker',
        externalId: undefined,
        folders: {}
    },

    /**
     * Logos
     */
    logos: {
        id: '60b9bb54-05c9-49fb-a07b-3e052d600cd3',
        name: 'Logos',
        externalId: undefined,
        folders: {}
    },

    /**
     * LUX
     */
    lUX: {
        id: '21c7b0d7-8e32-41ff-ac1a-bf6596140b5b',
        name: 'LUX',
        externalId: undefined,
        folders: {}
    },

    /**
     * Spec Sheets
     */
    specSheets: {
        id: '3b97f2f0-3120-44b6-89f8-637400ba4814',
        name: 'Spec Sheets',
        externalId: undefined,
        folders: {}
    },

    /**
     * Streetrod Lux
     */
    streetrodLux: {
        id: '8211f118-f85f-46b8-b3cf-385f412b8fd6',
        name: 'Streetrod Lux',
        externalId: undefined,
        folders: {}
    },

    /**
     * Upfits
     */
    upfits: {
        id: '956cc2e0-b2ec-442e-ab27-ae916334ba5e',
        name: 'Upfits',
        externalId: undefined,
        folders: {}
    },

    /**
     * Workhorse W4 CC
     */
    workhorseW4CC: {
        id: '4ea2c0b2-43ef-43b8-a899-1d7565d98681',
        name: 'Workhorse W4 CC',
        externalId: undefined,
        folders: {}
    }
} as const;
