/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const collections = {
    /**
     * Charger
     */
    charger: {
        codename: 'charger',
        id: '2b5483af-1514-4475-ad18-3cf8fdb195aa',
        name: 'Charger'
    },

    /**
     * Default
     */
    default: {
        codename: 'default',
        id: '00000000-0000-0000-0000-000000000000',
        name: 'Default'
    },

    /**
     * Paint
     */
    paint: {
        codename: 'paint',
        id: '0d9cab78-0fc8-46d7-9ba5-a4ac42ae5dbf',
        name: 'Paint'
    }
} as const;
