/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const contentTypeSnippets = {
    /**
     * Customization Option Basic Details
     */
    customization_option_basic_details: {
        codename: 'customization_option_basic_details',
        id: '6654bdab-2c77-428b-a357-2a1d2e59599d',
        externalId: undefined,
        name: 'Customization Option Basic Details',
        elements: {
            /**
             * Title (text)
             */
            customization_option_basic_details__title: {
                codename: 'customization_option_basic_details__title',
                id: '63bfb610-1d26-43ed-b055-c59b1eea424b',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            },

            /**
             * Image (asset)
             */
            customization_option_basic_details__image: {
                codename: 'customization_option_basic_details__image',
                id: '90f6dc19-08ce-49f5-ac33-9d380270056f',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Option Image (asset)
             */
            customization_option_basic_details__option_image: {
                codename: 'customization_option_basic_details__option_image',
                id: 'b108c3b6-5404-4154-9710-adefbc8bfd12',
                externalId: undefined,
                name: 'Option Image',
                required: false,
                type: 'asset'
            },

            /**
             * Description (rich_text)
             */
            customization_option_basic_details__description: {
                codename: 'customization_option_basic_details__description',
                id: 'cd54650e-3337-420a-a0b5-afbe3b73e585',
                externalId: undefined,
                name: 'Description',
                required: false,
                type: 'rich_text'
            }
        }
    },

    /**
     * GVWR
     */
    gvwr: {
        codename: 'gvwr',
        id: '199811dd-36ef-46be-af35-12fe05dc61c5',
        externalId: undefined,
        name: 'GVWR',
        elements: {
            /**
             * GVWR Value (number)
             *
             * Enter value in number
             */
            gvwr__gvwr_value: {
                codename: 'gvwr__gvwr_value',
                id: '5b77bdda-5cda-4ec7-8030-73a666ebcee4',
                externalId: undefined,
                name: 'GVWR Value',
                required: true,
                type: 'number'
            },

            /**
             * GVWR Unit (multiple_choice)
             */
            gvwr__gvwr_unit: {
                codename: 'gvwr__gvwr_unit',
                id: 'ee48c526-39b2-42df-b5c8-b3376d7b85a9',
                externalId: undefined,
                name: 'GVWR Unit',
                required: true,
                type: 'multiple_choice'
            }
        }
    },

    /**
     * leadtime
     */
    leadtime: {
        codename: 'leadtime',
        id: '5cf10c73-97b5-43d8-83aa-1fcdd7f7a185',
        externalId: undefined,
        name: 'leadtime',
        elements: {
            /**
             * Leadtime Value (number)
             *
             * Value in number
             */
            leadtime__value: {
                codename: 'leadtime__value',
                id: 'dd134e54-ed69-48d2-aed1-823a9660e944',
                externalId: undefined,
                name: 'Leadtime Value',
                required: false,
                type: 'number'
            },

            /**
             * Leadtime Unit (multiple_choice)
             */
            leadtime__leadtime_unit: {
                codename: 'leadtime__leadtime_unit',
                id: '0563eeea-e128-445f-b02a-d867f12bffaa',
                externalId: undefined,
                name: 'Leadtime Unit',
                required: true,
                type: 'multiple_choice'
            }
        }
    },

    /**
     * Payload Capacity
     */
    payload_capacity: {
        codename: 'payload_capacity',
        id: 'b82ff58b-b443-460d-bb27-eace978ef173',
        externalId: undefined,
        name: 'Payload Capacity',
        elements: {
            /**
             * Payload Capacity Value (number)
             */
            payload_capacity__payload_capacity_value: {
                codename: 'payload_capacity__payload_capacity_value',
                id: '1d9f91a5-7471-42f9-9b38-a0971ce9fdbf',
                externalId: undefined,
                name: 'Payload Capacity Value',
                required: true,
                type: 'number'
            },

            /**
             * Payload Capacity Unit (multiple_choice)
             */
            payload_capacity__payload_capacity_unit: {
                codename: 'payload_capacity__payload_capacity_unit',
                id: 'b5aa15bd-5f9b-49c7-848a-b3c1043c2869',
                externalId: undefined,
                name: 'Payload Capacity Unit',
                required: true,
                type: 'multiple_choice'
            }
        }
    },

    /**
     * price snippet
     */
    price: {
        codename: 'price',
        id: 'e4b9e350-23cf-4b0d-ac85-02d30776edaf',
        externalId: undefined,
        name: 'price snippet',
        elements: {
            /**
             * MSRP Price Value (number)
             *
             * Value in number
             */
            price__value: {
                codename: 'price__value',
                id: 'c15b8589-4a2f-4dfd-bc7b-4e477ab2ebba',
                externalId: undefined,
                name: 'MSRP Price Value',
                required: true,
                type: 'number'
            },

            /**
             * MSRP Price Unit (multiple_choice)
             */
            price__price_unit: {
                codename: 'price__price_unit',
                id: 'b8a6b469-6984-4ee7-8712-9851b4a739b7',
                externalId: undefined,
                name: 'MSRP Price Unit',
                required: true,
                type: 'multiple_choice'
            },

            /**
             * Dealer Price Value (number)
             */
            price__dealer_price_value: {
                codename: 'price__dealer_price_value',
                id: 'fa87a0a8-c7ae-41e5-b989-2b94e9364aad',
                externalId: undefined,
                name: 'Dealer Price Value',
                required: true,
                type: 'number'
            },

            /**
             * Dealer Price Unit (multiple_choice)
             */
            price__dealer_price_unit: {
                codename: 'price__dealer_price_unit',
                id: '1f2904b9-7d57-4e96-95c2-d29d30bf6858',
                externalId: undefined,
                name: 'Dealer Price Unit',
                required: true,
                type: 'multiple_choice'
            }
        }
    },

    /**
     * weight
     */
    weight: {
        codename: 'weight',
        id: '40e39da7-9661-4289-90e0-9736923e22ed',
        externalId: undefined,
        name: 'weight',
        elements: {
            /**
             * Weight Value (number)
             *
             * Value in number
             */
            weight__value: {
                codename: 'weight__value',
                id: 'de29de67-a522-4acc-b489-0aedbc6d8a20',
                externalId: undefined,
                name: 'Weight Value',
                required: true,
                type: 'number'
            },

            /**
             * Weight Unit (multiple_choice)
             */
            weight__weight_unit: {
                codename: 'weight__weight_unit',
                id: '07b09b67-28c1-41c2-a87c-2c3f918c2a5f',
                externalId: undefined,
                name: 'Weight Unit',
                required: true,
                type: 'multiple_choice'
            }
        }
    }
} as const;
