/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const roles = {
    /**
     * Charging Partner
     */
    chargingPartner: {
        codename: undefined,
        id: '0e5a36f7-ab42-48ad-bff7-d5528d69ca46',
        name: 'Charging Partner'
    },

    /**
     * Dealer
     */
    dealer: {
        codename: undefined,
        id: 'd805a4a7-9aa4-44a9-91d4-8321b76da0fd',
        name: 'Dealer'
    },

    /**
     * Editor
     */
    editor: {
        codename: undefined,
        id: 'c9c4db39-e61a-4516-a8d3-ebcd28c0800b',
        name: 'Editor'
    },

    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '07972b56-6a37-4c63-bbcc-30d8ffabde79',
        name: 'Project manager'
    },

    /**
     * Upfitter
     */
    upfitter: {
        codename: undefined,
        id: 'a41f703c-3030-41a1-8147-d6141d9c47b5',
        name: 'Upfitter'
    },

    /**
     * Viewer
     */
    viewer: {
        codename: undefined,
        id: 'd10cea45-584e-4fa6-8b34-b8dd2fa88d1a',
        name: 'Viewer'
    }
} as const;
