/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const taxonomies = {
    /**
     * Chassis Type
     */
    chassis_type: {
        codename: 'chassis_type',
        id: 'fb52a7c7-1691-40f2-aa83-8c8d9d0aa452',
        externalId: undefined,
        name: 'Chassis Type',
        terms: {
            cab_chassis: {
                codename: 'cab_chassis',
                id: '7148757f-67e8-4d29-9d8f-cea521a9da07',
                externalId: undefined,
                name: 'Cab Chassis',
                terms: {}
            },
            strip_chassis: {
                codename: 'strip_chassis',
                id: 'd8259728-c3bb-4b04-a428-e3ce946e84c9',
                externalId: undefined,
                name: 'Strip Chassis',
                terms: {}
            }
        }
    },

    /**
     * Configuration Option Category
     */
    configuration_option_category: {
        codename: 'configuration_option_category',
        id: '3d0b907c-8952-4377-b730-5112c17d5d90',
        externalId: undefined,
        name: 'Configuration Option Category',
        terms: {
            accessories: {
                codename: 'accessories',
                id: '173e633d-2266-4750-93ef-41cea5336b27',
                externalId: undefined,
                name: 'Accessories',
                terms: {}
            },
            body_style: {
                codename: 'body_style',
                id: 'c7ca6c11-7102-4a44-80f7-05c0ae7de442',
                externalId: undefined,
                name: 'Body Style',
                terms: {}
            },
            charger: {
                codename: 'charger',
                id: 'b55944c0-c1ef-4477-b774-792d892dbfd9',
                externalId: undefined,
                name: 'Charger',
                terms: {}
            },
            chassis: {
                codename: 'chassis',
                id: 'b1ec2f68-9b7c-4a7e-be28-241c4aa26be6',
                externalId: undefined,
                name: 'Chassis',
                terms: {}
            },
            drivetrain: {
                codename: 'drivetrain',
                id: '423fcefe-c49b-4a0c-98b7-0bbe1ac73c39',
                externalId: undefined,
                name: 'Drivetrain',
                terms: {}
            },
            model: {
                codename: 'model',
                id: '8d88ed4e-0f6f-4932-8fce-93931f3d97ad',
                externalId: undefined,
                name: 'Model',
                terms: {}
            },
            others: {
                codename: 'others',
                id: 'e877810f-0353-4deb-b7f0-fda28bf22f71',
                externalId: undefined,
                name: 'Others',
                terms: {}
            },
            powertrain: {
                codename: 'powertrain',
                id: '079a8521-1fe6-4f11-8976-d77264c0317b',
                externalId: undefined,
                name: 'Powertrain',
                terms: {}
            },
            shelving: {
                codename: 'shelving',
                id: 'a73ecfee-0a85-46c1-bbee-ff14348b746f',
                externalId: undefined,
                name: 'Shelving',
                terms: {}
            },
            upfit: {
                codename: 'upfit',
                id: '7bc68716-d64e-4e11-825c-62010c109eaa',
                externalId: undefined,
                name: 'Upfit',
                terms: {}
            },
            upholstery: {
                codename: 'upholstery',
                id: 'dbda4e65-cecf-4f44-a3b3-1fd9f1b995ba',
                externalId: undefined,
                name: 'Upholstery',
                terms: {}
            }
        }
    },

    /**
     * Manufacturer
     */
    manufacturer: {
        codename: 'manufacturer',
        id: 'baf696cb-0310-4692-a38b-86c1b8a61405',
        externalId: undefined,
        name: 'Manufacturer',
        terms: {
            abb: {
                codename: 'abb',
                id: '2f50b798-b0c9-44d7-b0ab-71d9a0183560',
                externalId: undefined,
                name: 'ABB',
                terms: {}
            },
            aes: {
                codename: 'aes',
                id: '9228e501-b4a1-4929-9fb2-b3a94b21a73f',
                externalId: undefined,
                name: 'AES',
                terms: {}
            },
            chargepoint: {
                codename: 'chargepoint',
                id: '925cfef8-d136-48dc-b268-314628a323b6',
                externalId: undefined,
                name: 'ChargePoint',
                terms: {}
            },
            eavx: {
                codename: 'eavx',
                id: '49a4bfdf-1efd-4b84-b73b-1459b8ddd979',
                externalId: undefined,
                name: 'EAVX',
                terms: {}
            },
            eavx_test: {
                codename: 'eavx_test',
                id: 'f01ac2b4-b8ce-46be-85a7-b8fbef7f4d11',
                externalId: undefined,
                name: 'EAVX Test',
                terms: {}
            },
            eavx_reading: {
                codename: 'eavx_reading',
                id: '51a5a389-7183-417c-a775-42c6366bfb81',
                externalId: undefined,
                name: 'EAVX/READING',
                terms: {}
            },
            eby: {
                codename: 'eby',
                id: 'a1db1420-3cdd-4cf5-847a-a0a15b7b9b0f',
                externalId: undefined,
                name: 'EBY',
                terms: {}
            },
            hackney: {
                codename: 'hackney',
                id: '9744d2f1-92a5-4e38-ad0e-fe7dec9845d6',
                externalId: undefined,
                name: 'Hackney',
                terms: {}
            },
            knapheide: {
                codename: 'knapheide',
                id: '7e4ee687-eb5c-41ae-9b41-b0a1cbbe2b39',
                externalId: undefined,
                name: 'Knapheide',
                terms: {}
            },
            local_manufacturer: {
                codename: 'local_manufacturer',
                id: '6192ac83-6640-4b4b-9215-3a4b41d89d22',
                externalId: undefined,
                name: 'Local Manufacturer',
                terms: {}
            },
            morgan_corp: {
                codename: 'morgan_corp',
                id: 'f8647346-1822-4a46-8484-b7a1de66e98f',
                externalId: undefined,
                name: 'Morgan Corp',
                terms: {}
            },
            noco: {
                codename: 'noco',
                id: 'b25d1383-e2de-493a-9d5b-9e30ef4b4783',
                externalId: undefined,
                name: 'NOCO',
                terms: {}
            },
            stellar: {
                codename: 'stellar',
                id: 'd346d8bb-6d53-493e-8e34-9c45826ce665',
                externalId: undefined,
                name: 'Stellar',
                terms: {}
            },
            stonebrooke: {
                codename: 'stonebrooke',
                id: '4394d545-196b-4e67-afe1-a937777b4b80',
                externalId: undefined,
                name: 'Stonebrooke',
                terms: {}
            },
            subzero: {
                codename: 'subzero',
                id: '950e32d0-6114-44d6-a871-581fe0734480',
                externalId: undefined,
                name: 'SubZero',
                terms: {}
            }
        }
    },

    /**
     * Pool Inventory Reservation Status
     */
    pool_inventory_reservation_status: {
        codename: 'pool_inventory_reservation_status',
        id: 'b8221e99-47ed-4438-b9aa-1dd7e88e167d',
        externalId: undefined,
        name: 'Pool Inventory Reservation Status',
        terms: {
            available: {
                codename: 'available',
                id: '93883f40-51bb-4022-8684-29f42813a78c',
                externalId: undefined,
                name: 'Available',
                terms: {}
            },
            closed: {
                codename: 'closed',
                id: 'adeb2fd7-cf87-49de-ab16-7461fd1b23b2',
                externalId: undefined,
                name: 'Closed',
                terms: {}
            },
            reserved: {
                codename: 'reserved',
                id: '1766a07f-5743-418c-b8be-ac800f95ff89',
                externalId: undefined,
                name: 'Reserved',
                terms: {}
            }
        }
    },

    /**
     * Quote Statuses
     */
    quote_status: {
        codename: 'quote_status',
        id: '95cce1e9-530d-434d-b39f-7af6fcd61112',
        externalId: undefined,
        name: 'Quote Statuses',
        terms: {
            closed: {
                codename: 'closed',
                id: '570bf601-c43b-4e39-80fc-2c7a737d9dec',
                externalId: undefined,
                name: 'Closed',
                terms: {}
            },
            delivered: {
                codename: 'delivered',
                id: '2de7d734-cf41-4f20-b5c4-e210c67ca7f2',
                externalId: undefined,
                name: 'Delivered',
                terms: {}
            },
            in_production: {
                codename: 'in_production',
                id: '7f912cf6-3cf2-4f49-a448-1b13913d46ca',
                externalId: undefined,
                name: 'In Production',
                terms: {}
            },
            in_transit: {
                codename: 'in_transit',
                id: '71cb3993-71ce-4f76-9647-1a3146cb31ab',
                externalId: undefined,
                name: 'In Transit',
                terms: {}
            },
            order_processing: {
                codename: 'order_processing',
                id: 'f2fdc0b5-e424-42a6-9d41-4cbdf3170e7c',
                externalId: undefined,
                name: 'Order Processing',
                terms: {}
            },
            quote_accepted: {
                codename: 'quote_accepted',
                id: 'e7d7d745-5afb-487d-a26e-74f6e9aefb21',
                externalId: undefined,
                name: 'Quote Accepted',
                terms: {}
            },
            quote_generated: {
                codename: 'quote_generated',
                id: '19494668-006a-4a81-8582-0e2725fedcb2',
                externalId: undefined,
                name: 'Quote Generated',
                terms: {}
            }
        }
    },

    /**
     * Vehicle Make
     */
    vehicle_make: {
        codename: 'vehicle_make',
        id: '0d585ea9-d77b-452f-a774-d7757db1f908',
        externalId: undefined,
        name: 'Vehicle Make',
        terms: {
            fernhay: {
                codename: 'fernhay',
                id: '2949cf52-19d1-420d-aa2b-2a66200321b6',
                externalId: undefined,
                name: 'Fernhay',
                terms: {}
            },
            streetrod: {
                codename: 'streetrod',
                id: '724697f9-4e76-4139-b8f4-cc147822e2cc',
                externalId: undefined,
                name: 'Streetrod',
                terms: {}
            }
        }
    },

    /**
     * Vehicle Model
     */
    vehicle_model: {
        codename: 'vehicle_model',
        id: '07296820-f139-4c91-ac6e-70466be64830',
        externalId: undefined,
        name: 'Vehicle Model',
        terms: {
            equad: {
                codename: 'equad',
                id: '8c03561e-ccf8-4a71-94a1-b3dadbe153a2',
                externalId: undefined,
                name: 'eQuad',
                terms: {}
            },
            ewalker: {
                codename: 'ewalker',
                id: 'b04becfe-5efd-4ffd-b851-4d1ac3cc9b2e',
                externalId: undefined,
                name: 'eWalker',
                terms: {}
            },
            grit: {
                codename: 'grit',
                id: 'cca3997e-7765-4a00-aae2-2f1b8599e1f4',
                externalId: undefined,
                name: 'Grit',
                terms: {}
            },
            lux: {
                codename: 'lux',
                id: '57a6d4ff-1195-4fc0-9848-365d11a10156',
                externalId: undefined,
                name: 'Lux',
                terms: {}
            },
            vintage: {
                codename: 'vintage',
                id: 'ceff10e3-ef49-4826-a437-a4dfc94c76fb',
                externalId: undefined,
                name: 'Vintage',
                terms: {}
            }
        }
    },

    /**
     * Vocation
     */
    vocation: {
        codename: 'vocation',
        id: '657ed971-6802-4d1b-890d-6beb47499ba6',
        externalId: undefined,
        name: 'Vocation',
        terms: {
            construction___maintenance: {
                codename: 'construction___maintenance',
                id: '0561e37a-8c53-41cf-ab15-ff10a59a19ed',
                externalId: undefined,
                name: 'Construction & Maintenance',
                terms: {}
            },
            industrial_services: {
                codename: 'industrial_services',
                id: '4b5463b2-c74c-4b6e-a834-faa1da1692ae',
                externalId: undefined,
                name: 'Industrial Services',
                terms: {}
            },
            package_delivery: {
                codename: 'package_delivery',
                id: '06a00b3e-c560-4335-8624-9e6cf0b315e7',
                externalId: undefined,
                name: 'Package Delivery',
                terms: {}
            },
            utility_services: {
                codename: 'utility_services',
                id: 'a49f3819-6161-4538-ad55-20b210bf11ad',
                externalId: undefined,
                name: 'Utility Services',
                terms: {}
            }
        }
    }
} as const;
